Fix dependencies (#23)
* Revert "Dependencies: remove kotlin-compiler (#22)"

This reverts commit 65e1a819f0f41057dccbbcf7cf88ea6109ee34ae.

* Fix dependencies

Revert 65e1a819f0f41057dccbbcf7cf88ea6109ee34ae to fix 'org.jetbrains.kotlin.idea.KotlinFileType cannot be cast to org.jetbrains.kotlin.com.intellij.openapi.fileTypes.LanguageFileType' error. That error happens when using kotlin-compiler and kotlin-compiler-embeddable at the same time. However, if kotlin-compiler is removed, running Ank raises java.lang.NoClassDefFoundError: com/sun/jna/Native. This change recovers the use of kotlin-compiler and adds runtime dependencies from build.gradle instead of code.